### ISSUE TITLE
Unable to import snowflake pumls

### ISSUE THREAD

**Issue by ndanielsen** [plantuml-stdlib/gilbarbara-plantuml-sprites#6]
Just tried to import the snowflake related icons and they aren't included in the main or 1v branches. 

!includeurl SPRITESURL/snowflake.puml

**Comment by Potherca** [comment]
I'm not seeing this problem... Could this be because the main branch is called `master`, not `main`?

```plantuml
@startuml
!define SPRITESURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/sprites

!includeurl SPRITESURL/snowflake.puml

rectangle "<$snowflake>"
@enduml
```

![](https://www.plantuml.com/plantuml/png/JOv1guCm48Jl-HKgxwgvFnuFBpqKUYZQ_e0rMJLqNSDcWt-_2gKjp6NuPfXfau9eNiYK7iV0MFJNxdmxzVVkKiogCVrQAx0rKz0v3pcXk9KLMHktBZOIyD6kateAWvq23I2xeFwWA44nsGMIejYNDQOCx2Xxp49VepRnkeq43spYSSi8EWMU28lgx-SD_olJ8lizyGG0)

**Comment by ndanielsen** [comment]
@Potherca appreciate the example. I was following the readme and using v1.0. 

```
!define SPRITESURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.0/sprites
```
